### ISSUE TITLE
Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by jessedobbelaere** [yortus/DBFFile#35]
I read a bunch of DBF files successfully using your library (thanks for that!). However, I get an error on certain files

```
(node:79490) UnhandledPromiseRejectionWarning: Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:616:37)
    at Buffer.toString (buffer.js:804:14)
    at SBCSDecoder.write (/Users/MyUser/Code/ProjectName/node_modules/iconv-lite/encodings/sbcs-codec.js:68:19)
    at Object.decode (/Users/MyUser/Code/ProjectName/node_modules/iconv-lite/lib/index.js:42:23)
    at readRecordsFromDBF (/Users/MyUser/Code/ProjectName/node_modules/dbffile/dist/dbf-file.js:307:52)
```

This is more info about the old file (from a 1991 MS DOS application) using the python `dbf` package:

```
Table:         Test.DBF
Type:          dBase III Plus
Codepage:      ascii (plain ol' ascii)
Status:        DbfStatus.CLOSED
Last updated:  2020-05-23
Record count:  240
Field count:   18
Record length: 166
--Fields--
    0) nr N(4,0)
    1) klantnr N(4,0)
    2) faktype C(1)
    3) datum D
    4) tekst M
    5) netto N(7,0)
    6) btw N(7,0)
    7) totaal N(7,0)
    8) medecon N(7,0)
    9) netto1 N(7,0)
    10) netto2 N(7,0)
    11) netto3 N(7,0)
    12) netto4 N(7,0)
    13) netto5 N(7,0)
    14) uitvoer N(7,0)
    15) uitvoerneg N(7,0)
    16) betkode C(1)
    17) diversen C(60)
```
(I can send it if needed, 40kB).

I used this snippet of code to reproduce the error:

```typescript
import { DBFFile } from "dbffile";

(async function test() {
  const filePath = "Test.DBF";
  const dbf = await DBFFile.open(filePath, { encoding: "ascii" });

  const records = await dbf.readRecords(10);
})();
```
Also tried no encoding, and CP850 encoding and some other options, but not sure if it's encoding related? Providing no encoding at all (default latin) worked for the other files of the same database.

**Comment by yortus** [comment]
Hi @jessedobbelaere, I'm happy to investigate if you can sent me a file that repros the issue. You can sent it to my email address. Let me know whether it needs to be kept private or can be added to the test suite.

**Comment by jessedobbelaere** [comment]
Appreciate it! I sent an email with the file 👍 🙌

**Comment by yortus** [comment]
Hey @jessedobbelaere, I've published v1.4.2 with a small fix that should resolve this issue. Can you try it out?

**Comment by jessedobbelaere** [comment]
Thanks a lot! It seems to process the files much better now 👍 

It gets past most files now, but still crashes on some files from 1993-2001 with `Error reading memo file (read past end).`. Should I make another issue for that? Could print these out:

```
blockIndex 795
memoBlockSize 512
memoFilesize 406852
```

The error gets thrown here:
https://github.com/yortus/DBFFile/blob/5d6cf8a709dbb6d1522d794dfe4c3b6462601c4b/src/dbf-file.ts#L365-L368

so it gets into the conditional that throws the error... Just no clue about dBase files low-level what this means. I changed the `throw new Error` to a `break` and funny enough it seemed to work and I have all the records with what seems to be correct data. Just not sure about the consequences of ignoring this error.

**Comment by yortus** [comment]
Ok then, sounds like some progress but still not quite there. I haven't had many `.dbt` files to work with so even though the unit tests pass for the ones I have, there are clearly some wrong assumptions in the code regarding the file format. Would it be possible for you to send me another file that is hitting errors?

**Comment by yortus** [comment]
Hey @jessedobbelaere, I've published v1.4.3, which now reads the files you sent me without errors. I made a note about the fix [here](https://github.com/yortus/DBFFile/blob/141e78a3e1a1f348961c6e8f41fa8d86d0ab69fa/src/dbf-file.ts#L335-L342) - it's low-level stuff, but my guess is that these files were modified by both dBase and FoxPro at different times.

Can you try it out and let me know if it works as expected now?

I haven't added any of the files you sent me to the test suite, although I'd really like to add them since they throw up cases that weren't covered before. I actually don't have any software to modify them in-place to remove PII. If you are able to do that and sent through PII-free files for the test suite, I'd be very grateful, but only if you have the time and software for it.

**Comment by jessedobbelaere** [comment]
Awesome, everything works great now in my Node app to migrate the data 👍 👍 🥇 
![image](https://user-images.githubusercontent.com/1352979/83006027-e54ae380-a011-11ea-9b13-72dbca989726.png)

Not sure why it would have both dBase and FoxPro markers. This is an MS DOS UI application (dBase?), custom made back in 1990 probably. Maybe the IT guy at the time made some tweaks in the '90's to the code and used Fox Pro on some of them.

I'll give it a try to anonymize the files so I can add them to the test suite 🙌
